---
name: Build Salt Onedir

on:
  workflow_call:
    inputs:
      salt-version:
        type: string
        required: true
        description: The Salt version to set prior to building packages.
      github-hosted-runners:
        type: boolean
        required: true
      self-hosted-runners:
        type: boolean
        required: true
      cache-seed:
        required: true
        type: string
        description: Seed used to invalidate caches
      relenv-version:
        required: true
        type: string
        description: The version of relenv to use
      python-version:
        required: true
        type: string
        description: The version of python to use with relenv

env:
  RELENV_DATA: "${{ github.workspace }}/.relenv"

jobs:

  build-salt-linux:
    name: Linux
    strategy:
      fail-fast: false
      matrix:
        arch:
          - x86_64
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python Tools Scripts
        uses: ./.github/actions/setup-python-tools-scripts

      - name: Setup Salt Version
        id: setup-salt-version
        uses: ./.github/actions/setup-salt-version
        with:
          salt-version: "${{ inputs.salt-version }}"

      - name: Setup Relenv
        uses: ./.github/actions/setup-relenv
        id: setup-relenv
        with:
          platform: linux
          arch: ${{ matrix.arch }}
          version: ${{ inputs.relenv-version }}
          cache-seed: ${{ inputs.cache-seed }}
          python-version: ${{ inputs.python-version }}

      - name: Install Salt into Relenv Onedir
        uses: ./.github/actions/build-onedir-salt
        with:
          platform: linux
          arch: ${{ matrix.arch }}
          salt-version: "${{ inputs.salt-version }}"
          python-version: "${{ inputs.python-version }}"
          cache-prefix: ${{ inputs.cache-seed }}|relenv|${{ steps.setup-relenv.outputs.version }}

