---
name: Build Packaging Dependencies Onedir

on:
  workflow_call:
    inputs:
      salt-version:
        type: string
        required: true
        description: The Salt version to set prior to building packages.
      github-hosted-runners:
        type: boolean
        required: true
      self-hosted-runners:
        type: boolean
        required: true
      cache-seed:
        required: true
        type: string
        description: Seed used to invalidate caches
      relenv-version:
        required: true
        type: string
        description: The version of relenv to use
      python-version:
        required: true
        type: string
        description: The version of python to use with relenv

env:
  RELENV_DATA: "${{ github.workspace }}/.relenv"

jobs:

  build-deps-linux:
    name: Linux
    strategy:
      fail-fast: false
      matrix:
        arch:
          - x86_64
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v3
      - name: Setup Relenv
        id: setup-relenv
        uses: ./.github/actions/setup-relenv
        with:
          platform: linux
          arch: ${{ matrix.arch }}
          version: ${{ inputs.relenv-version }}
          cache-seed: ${{ inputs.cache-seed }}
          python-version: ${{ inputs.python-version }}

      - name: Setup Python Tools Scripts
        uses: ./.github/actions/setup-python-tools-scripts

      - name: APT install required packages
        uses: ConorMacBride/install-package@v1
        with:
          apt: build-essential python3-pip python3-dev python2.7-dev libssl-dev ldap-utils libldap2-dev libsasl2-dev slapd python-tox lcov valgrind

      - name: Install Salt Packaging Dependencies into Relenv Onedir
        uses: ./.github/actions/build-onedir-deps
        with:
          platform: linux
          arch: ${{ matrix.arch }}
          python-version: "${{ inputs.python-version }}"
          cache-prefix: ${{ inputs.cache-seed }}|relenv|${{ steps.setup-relenv.outputs.version }}
